Update suiteCRM_8_Installation-latest

diff --git a/suiteCRM_8_Installation-latest b/suiteCRM_8_Installation-latest
--- a/suiteCRM_8_Installation-latest
+++ b/suiteCRM_8_Installation-latest
@@ -1,9 +1,8 @@
 #!/bin/bash
-#!/bin/sh
 #######################################
 # In case of any errors (e.g. MySQL) just re-run the script. Nothing will be re-installed except for the packages with errors.
 #######################################
-#  Written by Anoop Singh from https://www.hostingshades.com/
+#  Written By Anoop Singh from https://www.hostingshades.com/
 
 #COLORS
 # Reset
@@ -31,19 +30,28 @@ BWhite='\033[1;37m'       # White
 # Default Credentials
 ADMIN_DEF="admin"               # Defualt suitecrm admin user name
 ADMINPASS_DEF="admin@12345"     # Defualt suitecrm pass name
-date=`date`
-prefix="tenant_"
+Date=`date`                     # Current date
+UNSC="_"                        # For Underscore 
+DB_NAME_PREFIX="tenant_"
+DNS_SUFFIX="circlecrm.cloud"
+DB_PASS_DEF="PassW0rd!"
 SUITECRM_VER="8.2.0"            # Latest stable version of SuiteCRM from https://github.com/salesagility/SuiteCRM-Core.git/
-################################
 
-#.1....###### MYSQL SHOW
+# Check if running as root  
+ if [ "$(id -u)" != "0" ]; then  
+   echo -e "$BRed This script must be run as root $Color_Off" 1>&2  
+   exit 1  
+ fi  
+
+
 
 #.2....###### READING DATA FROM USER ######
 echo -en "$BWhite \n Please Enter SuiteCRM Company Name                        :$BGreen"
-read COMPANY
+read COMPANY_LOWER
 
-echo -en "$BWhite \n Please Enter SuiteCRM Domain Name Or DNS Name/Entry       :$BGreen"
-read DOMAIN_NAME
+
+# echo -en "$BWhite \n Please Enter SuiteCRM Domain Name Or DNS Name/Entry       :$BGreen"
+# read DOMAIN_NAME
 
 echo -e "$BCyan-----------------------------Printing Databases ------------------------------------$Color_Off"
 sleep 2   
@@ -52,14 +60,17 @@ mysql -u root -e "SHOW DATABASES LIKE 'tenant%';"
  
 
 
-echo -en "$BWhite Please Enter SuiteCRM Databases Name                      :$BYellow"$prefix
- read DB_NAME
+echo -en "$BWhite Please Enter SuiteCRM Databases Name                      :$BYellow"$DB_NAME_PREFIX
+read DB_NAME_LOWER
 
-echo -en "$BWhite Please Enter SuiteCRM Databases Username                  :$BYellow"$prefix
-read DB_USER
 
-echo -en "$BWhite Please Enter SuiteCRM Databases Password                  :$BGreen"
+echo -en "$BWhite Please Enter SuiteCRM Databases Username                  :$BYellow"$DB_NAME_PREFIX
+read DB_USER_LOWER
+
+
+echo -en "$BWhite Please Enter SuiteCRM Databases Password $BYellow(default $DB_PASS_DEF):$BGreen"
 read DB_PASSWD
+DB_PASSWD="${DB_PASSWD:-$DB_PASS_DEF}"
 
 echo -en "$BWhite Please Enter SuiteCRM Admin Name           $BYellow(default $ADMIN_DEF):$BGreen"
 read ADMIN
@@ -70,14 +81,24 @@ read ADMINPASS
 ADMINPASS="${ADMINPASS:-$ADMINPASS_DEF}"
 echo -e "$Color_Off"
 
+
+# LOWERCASE
+COMPANY=${COMPANY_LOWER,,}
+DB_NAME=${DB_NAME_LOWER,,}
+DB_USER=${DB_USER_LOWER,,}
+
+DB_NAME="$DB_NAME_PREFIX$DB_NAME$UNSC$COMPANY"
+DB_USER="$DB_NAME_PREFIX$DB_USER$UNSC$COMPANY"
+DNS="$COMPANY.$DNS_SUFFIX"
+
 echo -e "$BCyan------------------------------- SUMMARY OF INSTALLATION ---------------------------------$Color_Off"
 
 echo -en "$BGreen \n SuiteCRM Version            :$BYellow $SUITECRM_VER $Color_Off"
 echo -en "$BGreen \n Company Name                :$BYellow $COMPANY $Color_Off"
-echo -en "$BGreen \n SuiteCRM DNS Name           :$BYellow $COMPANY.$DOMAIN_NAME $Color_Off"
+echo -en "$BGreen \n SuiteCRM DNS Name           :$BYellow $DNS $Color_Off"
 # echo -en "$BGreen \n SuiteCRM Domain Name        :$BYellow $DOMAIN_NAME $Color_Off"
-echo -en "$BGreen \n SuiteCRM Databases Name     :$BYellow $prefix$DB_NAME $Color_Off"
-echo -en "$BGreen \n SuiteCRM Databases Username :$BYellow $prefix$DB_USER $Color_Off"
+echo -en "$BGreen \n SuiteCRM Databases Name     :$BYellow $DB_NAME $Color_Off"
+echo -en "$BGreen \n SuiteCRM Databases Username :$BYellow $DB_USER $Color_Off"
 echo -en "$BGreen \n SuiteCRM Databases Password :$BYellow $DB_PASSWD $Color_Off"
 echo -en "$BGreen \n SuiteCRM Admin Name         :$BYellow $ADMIN $Color_Off"
 echo -e "$BGreen \n SuiteCRM Admin Password     :$BYellow $ADMINPASS $Color_Off"
@@ -95,31 +116,29 @@ case $suite in
 echo -e "$BCyan----------------------------- Creating Vhost for The Domain -----------------------------$Color_Off"        
 sleep 2
 
-FILE=/etc/httpd/conf.d/$DOMAIN_NAME.conf     
+FILE=/etc/httpd/conf.d/$DNS.conf     
 if [ -f $FILE ]; then
-   echo -e "$BRed File $DOMAIN_NAME.conf already exists. Unable to create Vhost for the Domain $Color_Off" 1>&2 
+   echo -e "$BRed File $DNS.conf already exists. Unable to create Vhost for the Domain $Color_Off" 1>&2 
    
-   break 1
+   exit 1
 else
    echo "<VirtualHost *:80>
-    ServerAdmin admin@$DOMAIN_NAME
-    DocumentRoot "/var/www/html/$DOMAIN_NAME/public"
+    ServerAdmin $COMPANY@$DNS_SUFFIX
+    DocumentRoot "/var/www/html/$COMPANY/public"
     DirectoryIndex index.php index.php4 index.php5 index.htm index.html
-    ServerName $DOMAIN_NAME
-    ErrorLog "/var/log/httpd/$DOMAIN_NAME.error_log"
-    CustomLog "/var/log/httpd/$DOMAIN_NAME.access_log" common
-    <LocationMatch "^/(.*)">
-        Header always append X-Frame-Options SAMEORIGIN
-    </LocationMatch>
+    ServerName $DNS
+    ErrorLog "/var/log/httpd/$COMPANY.error_log"
+    CustomLog "/var/log/httpd/$COMPANY.access_log" common
+    
 
-     <Directory /var/www/html/$DOMAIN_NAME/public>
+     <Directory /var/www/html/$COMPANY/public>
         AllowOverride All
         Order Allow,Deny
         Allow from All
      </Directory>
 
     </VirtualHost>
-    " >/etc/httpd/conf.d/$DOMAIN_NAME.conf
+    " >/etc/httpd/conf.d/$DNS.conf
 fi
 
 
@@ -134,10 +153,10 @@ sleep 2
     echo -e "$BWhite We Suggest Trying the New Database Name $Color_Off"
     exit 1
   else
-    echo -e "$BYellow The Database Name $prefix$DB_NAME Has Been Created Successfully! $Color_Off"
-    mysql -u root  -e "CREATE DATABASE $prefix$DB_NAME";
-    mysql -u root  -e "CREATE USER '$prefix$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASSWD'";
-    mysql -u root  -e "GRANT ALL PRIVILEGES ON $prefix$DB_NAME.* TO '$prefix$DB_USER'@'localhost'";
+    echo -e "$BYellow The Database Name $DB_NAME Has Been Created Successfully! $Color_Off"
+    mysql -u root  -e "CREATE DATABASE $DB_NAME";
+    mysql -u root  -e "CREATE USER '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASSWD'";
+    mysql -u root  -e "GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'localhost'";
     mysql -u root  -e "FLUSH PRIVILEGES";
  fi
 
@@ -145,7 +164,7 @@ sleep 2
 echo -e "$BCyan---------------------------Installing SuiteCRM for $DOMAIN_NAME -------------------------$Color_Off"
 sleep 2   
     cd /var/www/html
-    mkdir $DOMAIN_NAME && cd $DOMAIN_NAME
+    mkdir $COMPANY && cd $COMPANY
     wget -qc https://suitecrm.com/download/128/suite82/561615/suitecrm-8-2-0-zip.zip
     unzip suitecrm-8-2-0-zip.zip
 
@@ -158,30 +177,30 @@ sleep 2
 
    
 
-    ./bin/console suitecrm:app:install -u "$ADMIN" -p "$ADMINPASS" -U "$prefix$DB_USER" -P "$DB_PASSWD" -H "localhost" -N "$prefix$DB_NAME" -S "https://$DOMAIN_NAME" -d "yes"
+    ./bin/console suitecrm:app:install -u "$ADMIN" -p "$ADMINPASS" -U "$DB_USER" -P "$DB_PASSWD" -H "localhost" -N "$DB_NAME" -S "https://$DNS" -d "yes"
 
     find . -type d -not -perm 2755 -exec chmod 2755 {} \;
     find . -type f -not -perm 0644 -exec chmod 0644 {} \;
     find . ! -user apache -exec chown apache:apache {} \;
     sudo chown -R apache:apache /var/www/html
 
-echo -en "$BGreen \n SuiteCRM Link      : $BYellow http://$DOMAIN_NAME $Color_Off"
+echo -en "$BGreen \n SuiteCRM Link      : $BYellow http://$DNS $Color_Off"
 echo -en "$BGreen \n SuiteCRM Admin User: $BYellow $ADMIN $Color_Off"
 echo -e "$BGreen \n SuiteCRM Admin Pass : $BYellow $ADMINPASS $Color_Off"
 
-echo -e "$BGreen \n SuiteCRM And Databases Details Have been Stored In $BYellow /var/www/html/$COMPANY.$DOMAIN_NAME.txt $Color_Off"
+echo -e "$BGreen \n SuiteCRM And Databases Details Have been Stored In $BYellow /var/www/html/$DNS.txt $Color_Off"
 
-echo "Creaction Date is: $date
+echo "Creaction Date is: $Date
 SuiteCRM_Admin_Details:
-SuiteCRM Link:http://$DOMAIN_NAME
+SuiteCRM Link:http://$DNS
 SuiteCRM Admin User:$ADMIN 
 SuiteCRM Admin Pass:$ADMINPASS
 
 DataBases_Details:
-Databases Name:  $prefix$DB_NAME
-Database UserName:$prefix$DB_USER
+Databases Name:  $DB_NAME
+Database UserName:$DB_USER
 Database Password:$DB_PASSWD
-" >/var/www/html/$COMPANY.$DOMAIN_NAME.txt
+" >/var/www/html/$DNS.txt
 sudo chown -R apache:apache /var/www/html
 
     break;;
@@ -199,15 +218,15 @@ done
 #.5.################# Install Let’s Encrypt with Apache ###########################
  
 while true; do
- DIR=/etc/letsencrypt/live/$DOMAIN_NAME
+ DIR=/etc/letsencrypt/live/$DNS
  echo -en "$BWhite Do you want to install SSL ? Yes or No ...: $BGreen"
  read ssl
  
       case $ssl in
             [yY][eE][sS]|[yY])
-echo -e "$BCyan------------------------ Installing Let's Encrypt for $DOMAIN_NAME ----------------------$Color_Off"
+echo -e "$BCyan------------------------ Installing Let's Encrypt for $DNS ----------------------$Color_Off"
 sleep 2                           
-                            certbot --apache -d $DOMAIN_NAME
+                            certbot --apache -d $DNS
                             
                             
                               if [ -d $DIR ]; then
@@ -230,3 +249,4 @@ sleep 2
 done
 
 ########################  END #####################################################
+
